### ISSUE TITLE
offlinewiki in smallmodeltemplate/Factualworkflow gives error

### ISSUE THREAD

**Issue by pointave** [SomeOddCodeGuy/WilmerAI#11]
I set **_current-user.json** to "smallmodeltemplate"
-Wilmerai server  Running on http://127.0.0.1:5005/ 
-OFFLINEWIKI  server Host: [0.0.0.0](http://0.0.0.0/) Port: 5728         *works with example curl cmds
-Starting Kobold API on port 5000 at http://localhost:5000/api/ Starting OpenAI Compatible API on port 5000 at http://localhost:5000/v1/     (***I'm running mistral-nemo or gemma27b locally) 

My **ApiType** is openAIV1Completion for Koboldcpp. (saw you preferred it so I think this is correct)
I believe I dont need to update any of the other configs since the routing with **smallmodelcategoriesconfig** has workflows that all have endpoint smallmodelendpoint which uses  "endpoint": "http://127.0.0.1:5000",.

In **sillytavern**, I set it to use chat completion with custom endpoint: http://192.168.1.213:5005/  which populates WilmerAi for the available model. *test message button comes back with an error though... 
In first tab I set context to 200k and set character names behavior to None because I set chatCompleteAddUserAssistant in the smallmodeltemplate to true. 
In the 'A' tab, I imported both instruct and context template, making sure to enable "check names" and "force for groups".
It does seem to route correctly, it uses conversational "Hi again! How can I help you today?<|im_start|>user" not always returning with the <im....> but frequently does, 
**but the factual workflow gives me this.**

Non-streaming output:  Japan history
######################################
------Workflow FactualWorkflow; step 2; node type: OfflineWikiApiFullArticle
Prompt processor Checkpoint

Config Type: OfflineWikiApiFullArticle
Offline Wikipedia Api Full Article
[192.168.1.200](http://192.168.1.200/) - - [07/Sep/2024 09:11:13] "POST /chat/completions HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\envs\wiki\lib\site-packages\werkzeug\serving.py", line 363, in run_wsgi
    execute(self.server.app)
  File "C:\Users\user\anaconda3\envs\wiki\lib\site-packages\werkzeug\serving.py", line 326, in execute
    for data in application_iter:
  File "C:\Users\user\anaconda3\envs\wiki\lib\site-packages\werkzeug\wsgi.py", line 256, in __next__
    return self._next()
  File "C:\Users\user\anaconda3\envs\wiki\lib\site-packages\werkzeug\wrappers\response.py", line 32, in _iter_encoded
    for item in iterable:
  File "C:\Users\user\Github\WilmerAI\Middleware\workflows\managers\workflow_manager.py", line 143, in gen
    agent_outputs[f'agent{idx + 1}Output'] = self._process_section(config, request_id,
  File "C:\Users\user\Github\WilmerAI\Middleware\workflows\managers\workflow_manager.py", line 277, in _process_section
    return prompt_processor_service.handle_offline_wiki_node(messages, config["promptToSearch"], agent_outputs)
  File "C:\Users\user\Github\WilmerAI\Middleware\workflows\processors\prompt_processor.py", line 356, in handle_offline_wiki_node
    config=config
NameError: name 'config' is not defined

Maybe I'm missing a file? There is a config file in the offlinewiki folder I have.
There are two jsons that I may need to edit to fix; smallmodeltemplates using _chatonly, smallmodelendpoint using chatml. Which one would I make mistral/gemma-27b?

Does my **factualworkflow** have something wrong with its wiki step?
  {
    "title": "Querying the offline wikipedia api",
    "agentName": "Wikipedia Search Api Agent Three",
    "promptToSearch": "{agent2Output}",            <maybe it should be called agent1Output
    "type": "OfflineWikiApiFullArticle"
  },

This is **smallmodeltemplate.json**
{
  "port": 5005,
  "stream": true,
  "customWorkflowOverride": false,                                  <tried true but same problem
  "customWorkflow": "FactualWorkflow",
  "routingConfig": "smallModelCategoriesConfig",
.......
.......
  "chatPromptTemplateName": "_chatonly",                    <should this change?
  "verboseLogging": false,
  "chatCompleteAddUserAssistant": true,                         <because in sillytavern its on none
  "chatCompletionAddMissingAssistantGenerator": false,
  "useOfflineWikiApi": false,                                              <should this be true?
  "offlineWikiApiHost": "127.0.0.1",
  "offlineWikiApiPort": 5728
}

I've also tried your bat files instead of using an anaconda environment

**Comment by SomeOddCodeGuy** [comment]
It's not a mistake on your end! I actually discovered this very bug a couple of days ago and the fix for it is going out in a code release I intend to do tonight or tomorrow.

About 2 weeks ago some code got pushed that had broken this, and I didn't notice it right away; I hadn't asked my assistant a factual question until earlier this week lol.

At the latest I intend to have this fix out by tomorrow, but I'm aiming to try to get it out today!

Btw, I put a discussion post up about this but I want to reiterate here too- if you want to protect your configs, make a backup of them. My push is a huge breaking change for current configs as I changed (and hopefully improved) lots of things, so I don't want you to lose a config if you're holding on to it.

Once I get the push out, lets loop back around and see if that resolves your issue.

**Comment by SomeOddCodeGuy** [comment]
This issue should be corrected now. 

As mentioned before, massive changes to the example users, but the old ones will still work if you want to just keep those; make sure to back them up. However, the new ones should be MUCH better and easier to maintain. Readme is updated with info.

**Comment by pointave** [comment]
Cool stuff. Pretty fantastic when it works, I've had it work a few times now, but sometimes it will direct to a random article other times it worked if worded differently. I'm thinking it should always write that it pulled the wiki article or say it used the factual workflow, at least on the bottom of the terminal. 

I'll try the routing with multiple models eventually. Thanks for sharing your project, its a nice new tool.

**Comment by SomeOddCodeGuy** [comment]
\

> Cool stuff. Pretty fantastic when it works, I've had it work a few times now, but sometimes it will direct to a random article other times it worked if worded differently. I'm thinking it should always write that it pulled the wiki article or say it used the factual workflow, at least on the bottom of the terminal.
> 
> I'll try the routing with multiple models eventually. Thanks for sharing your project, its a nice new tool.

I'll devote time this week to stress testing this functionality a bit to see if I can improve the prompts to be more resilient. I'll also add in to write the title of the article in the console that was pulled; that's a great idea.

Part of the problem with Wilmer as a whole is that it is very model dependent. Some models handle this great, especially the bigger ones, but some smaller need more help to get there. I've been so focused on my own use-cases that I haven't gone back to really work through the experience when using things like an 8b or 7b model, and I can absolutely see some of those getting some... interesting search queries back.

Let me see if, by next weekend, I can't come up with some improvements to the workflow/prompts to help make the results acceptable. And also get that article log in the terminal.

**Comment by pointave** [comment]
Have you seen "bespoke-minicheck"? For your prompt you type Document: blah blah blah and then Claim: Your question. It will then reply with yes or no depending if its factual or not. Supposedly just as accurate as gpt4, might be worth looking into incorporating.
