### ISSUE TITLE
[DiscussionId] section should be stripped out asap

### ISSUE THREAD

**Issue by jeffqg** [SomeOddCodeGuy/WilmerAI#5]
While looking at the chunks used for memory creation, I noticed the [DiscussionId] appears to be included in the message getting hashed. Depending on how users are inserting the DiscussionId, it may be moved around within one discussion (eg SillyTavern insert @ depth), causing the hash for a given message to change.

Examples from one discussion thread:
```
***************************************
Hashing message: Echo: This is the first message.
Hash is: 66cd80579c7338554736fe199752c94a01f4cf164a2f9e38deb2fa433d96c974
***************************************
Hashing message: User: This is the first message.[DiscussionId]676323[/DiscussionId]
Hash is: df4eedfd2c176a3001cd27a2e7e7385aa24bf887249a869196e072541f217d93
***************************************
```
after two more back & forths:
```
***************************************
Hashing message: Echo: This is the first message.[DiscussionId]676323[/DiscussionId]
Hash is: 860e0ae3451e1ee549862afaae604e903e740be3b2b434b12764d52a4584e373
***************************************
Hashing message: User: This is the first message.
Hash is: 2129a02cade715f56e1ffb89caf6ecff0f0b59bb0f0f3de5c361833b3c09b16f
***************************************
```

**Comment by SomeOddCodeGuy** [comment]
I had a couple hours free this evening so I hopped in and took a shot at fixing this. I've cleaned up the discussionid removal and extraction so that it should properly removed from everything.

I pushed the update to the workflow_locks branch. I was only able to test it a few times but it looks like it's working pretty well. Let me know if you see anything crazy or acting funny.

**Comment by SomeOddCodeGuy** [comment]
This is now merged into master along with workflow locks by pull [request #7 ](https://github.com/SomeOddCodeGuy/WilmerAI/pull/7)
